// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64Drqtc3EzOjOC7oOzM_TDnJzxIwTmOo',
    appId: '1:342620535954:web:62f2d307d7d289b9cdba4b',
    messagingSenderId: '342620535954',
    projectId: 'kirana-grocery-app',
    authDomain: 'kirana-grocery-app.firebaseapp.com',
    storageBucket: 'kirana-grocery-app.firebasestorage.app',
    measurementId: 'G-R9TKNR2BH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMligHCWtvcCeYEFL3ROr4g44k5rNmi-E',
    appId: '1:342620535954:android:d915f003ddc71d49cdba4b',
    messagingSenderId: '342620535954',
    projectId: 'kirana-grocery-app',
    storageBucket: 'kirana-grocery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbnTaKDFVud8wNAlg7oMPtCfK69O5otFM',
    appId: '1:342620535954:ios:74acfecfe4d99759cdba4b',
    messagingSenderId: '342620535954',
    projectId: 'kirana-grocery-app',
    storageBucket: 'kirana-grocery-app.firebasestorage.app',
    iosBundleId: 'com.example.kirana',
  );
}
